#########################################################
### Branches for cfA
#########################################################

import FWCore.ParameterSet.Config as cms

basicKinematicLeaves = cms.PSet(
    status = cms.string('status'),
    phi = cms.string('phi'),
    pt = cms.string('pt'),
    pz = cms.string('pz'),
    px = cms.string('px'),
    py = cms.string('py'),
    eta = cms.string('eta'),
    theta = cms.string('theta'),
    et = cms.string('et'),
    energy = cms.string('energy')
)

configurableAnalysis = cms.EDFilter("ConfigurableAnalysis",
    Selections = cms.PSet(
        filters = cms.PSet(),
        selections = cms.PSet(
            minSelection = cms.PSet(
                filterOrder = cms.vstring(''),
                makeFinalPlots = cms.bool(True),
                makeSummaryTable = cms.bool(True),
                makeContentPlots = cms.bool(True),
                makeAllButOnePlots = cms.bool(True),
                ntuplize = cms.bool(True),
                nMonitor = cms.uint32(1000),
                makeCumulativePlots = cms.bool(True)
            )
        )
    ),
    Plotter = cms.PSet(
        TH1s = cms.PSet(),
        ComponentName = cms.string('VariablePlotter'),
        TProfiles = cms.PSet(),
        TH2s = cms.PSet()
    ),
    Variables = cms.PSet(
        L1Bit = cms.PSet(
            src = cms.InputTag("gtDigis"),
            method = cms.string('ComputedVariable'),
            computer = cms.string('L1BitComputer')
        )
    ),
    workAsASelector = cms.bool(True),
    flows = cms.vstring('minSelection'),
    Ntupler = cms.PSet(
        branchesPSet = cms.PSet(
            treeName = cms.string('eventB'),
            pv = cms.PSet(
                src = cms.InputTag("offlineSlimmedPrimaryVertices"),
                 leaves = cms.PSet(
                       vars = cms.vstring(
                          'x:x',
                          'y:y',
                          'z:z',
                          'xErr:xError',
                          'yErr:yError',
                          'zErr:zError',
                          'chi2:chi2',
                          'ndof:ndof',
                          'isFake:isFake',               
                          'isValid:isValid',
                          'tracksSize:tracksSize'
											 
               		),
               ),
               Class = cms.string('reco::Vertex'),
            ),
            beamSpot = cms.PSet(  
           	src = cms.InputTag("offlineBeamSpot"),
            leaves = cms.PSet(
                vars = cms.vstring(
                     'x:position.x',
                     'y:position.y',
                     'z:position.z',
                     'x0Error:x0Error',
                     'y0Error:y0Error',
                     'z0Error:z0Error',
                     'sigmaZ:sigmaZ',
                     'sigmaZ0Error:sigmaZ0Error',
                     'dxdz:dxdz',
                     'dxdzError:dxdzError',
                     'dydz:dydz',
                     'dydzError:dydzError',
                     'beamWidthX:BeamWidthX',#addedFB
                     'beamWidthY:BeamWidthY',#addedFB
                     #'beamWidth:BeamWidth',
                     'beamWidthXError:BeamWidthXError',#addedFB
                     'beamWidthYError:BeamWidthYError'#addedFB
                     #'beamWidthError:BeamWidthError'
                       )
                ),
            Class = cms.string('reco::BeamSpot')
            ),

            mus = cms.PSet(
                src = cms.InputTag('slimmedMuons'),
                leaves = cms.PSet(
                    basicKinematicLeaves,
                    vars = cms.vstring(
                        'nPFmatch:numberOfSourceCandidatePtrs()',
                        'gen_id:genLepton.pdgId',
                        'gen_phi:genLepton.phi',
                        'gen_pt:genLepton.pt',
                        'gen_pz:genLepton.pz',
                        'gen_px:genLepton.px',
                        'gen_py:genLepton.py',
                        'gen_eta:genLepton.eta',
                        'gen_theta:genLepton.theta',
                        'gen_et:genLepton.et',                       
                        'gen_mother_id:genLepton.mother.pdgId',
                        'gen_mother_phi:genLepton.mother.phi',
                        'gen_mother_pt:genLepton.mother.pt',
                        'gen_mother_pz:genLepton.mother.pz',
                        'gen_mother_px:genLepton.mother.px',
                        'gen_mother_py:genLepton.mother.py',
                        'gen_mother_eta:genLepton.mother.eta',
                        'gen_mother_theta:genLepton.mother.theta',
                        'gen_mother_et:genLepton.mother.et',                       
                        'tkHits:track.hitPattern.numberOfValidHits', 
                        'cIso:caloIso', 
                        'tIso:trackIso',
                        'ecalIso:ecalIso',
                        'hcalIso:hcalIso',
                        'ecalvetoDep:ecalIsoDeposit.candEnergy',
                        'hcalvetoDep:hcalIsoDeposit.candEnergy',
#                        'id:leptonID', 
                        'calEnergyEm:calEnergy.em',
                        'calEnergyHad:calEnergy.had',
                        'calEnergyHo:calEnergy.ho',
                        'calEnergyEmS9:calEnergy.emS9',
                        'calEnergyHadS9:calEnergy.hadS9',
                        'calEnergyHoS9:calEnergy.hoS9', 
                        'iso03_emVetoEt:isolationR03.emVetoEt', 	 
                        'iso03_hadVetoEt:isolationR03.hadVetoEt',
                        'iso03_sumPt:isolationR03.sumPt',
                        'iso03_emEt:isolationR03.emEt',
                        'iso03_hadEt:isolationR03.hadEt',
                        'iso03_hoEt:isolationR03.hoEt',
                        'iso03_nTracks:isolationR03.nTracks',
                        'iso05_sumPt:isolationR05.sumPt',
                        'iso05_emEt:isolationR05.emEt',
                        'iso05_hadEt:isolationR05.hadEt',
                        'iso05_hoEt:isolationR05.hoEt',
                        'iso05_nTracks:isolationR05.nTracks',
                        'pfIsolationR03_sumChargedHadronPt:pfIsolationR03.sumChargedHadronPt',
                        'pfIsolationR03_sumChargedParticlePt:pfIsolationR03.sumChargedParticlePt',
                        'pfIsolationR03_sumNeutralHadronEt:pfIsolationR03.sumNeutralHadronEt',
                        'pfIsolationR03_sumNeutralHadronEtHighThreshold:pfIsolationR03.sumNeutralHadronEtHighThreshold',
                        'pfIsolationR03_sumPhotonEt:pfIsolationR03.sumPhotonEt',
                        'pfIsolationR03_sumPhotonEtHighThreshold:pfIsolationR03.sumPhotonEtHighThreshold',
                        'pfIsolationR03_sumPUPt:pfIsolationR03.sumPUPt',
                        'pfIsolationR04_sumChargedHadronPt:pfIsolationR04.sumChargedHadronPt',
                        'pfIsolationR04_sumChargedParticlePt:pfIsolationR04.sumChargedParticlePt',
                        'pfIsolationR04_sumNeutralHadronEt:pfIsolationR04.sumNeutralHadronEt',
                        'pfIsolationR04_sumNeutralHadronEtHighThreshold:pfIsolationR04.sumNeutralHadronEtHighThreshold',
                        'pfIsolationR04_sumPhotonEt:pfIsolationR04.sumPhotonEt',
                        'pfIsolationR04_sumPhotonEtHighThreshold:pfIsolationR04.sumPhotonEtHighThreshold',
                        'pfIsolationR04_sumPUPt:pfIsolationR04.sumPUPt',
                        'charge:charge', 
                        'cm_chi2:combinedMuon.chi2', 
                        'cm_ndof:combinedMuon.ndof', 
                        'cm_chg:combinedMuon.charge', 
                        'cm_pt:combinedMuon.pt', 
                        'cm_px:combinedMuon.px', 
                        'cm_py:combinedMuon.py', 
                        'cm_pz:combinedMuon.pz', 
                        'cm_eta:combinedMuon.eta', 
                        'cm_phi:combinedMuon.phi', 
                        'cm_theta:combinedMuon.theta', 
                        'cm_d0dum:combinedMuon.d0', 
                        'cm_dz:combinedMuon.dz', 
                        'cm_vx:combinedMuon.vx', 
                        'cm_vy:combinedMuon.vy', 
                        'cm_vz:combinedMuon.vz', 
                        'cm_numvalhits:combinedMuon.numberOfValidHits', 
                        'cm_numlosthits:combinedMuon.numberOfLostHits', 
                        'cm_numvalMuonhits:combinedMuon.hitPattern.numberOfValidMuonHits',
                        'cm_d0dumErr:combinedMuon.d0Error', 
                        'cm_dzErr:combinedMuon.dzError', 
                        'cm_ptErr:combinedMuon.ptError', 
                        'cm_etaErr:combinedMuon.etaError', 
                        'cm_phiErr:combinedMuon.phiError', 
                        'tk_id:track.key',
                        'tk_chi2:track.chi2',
                        'tk_ndof:track.ndof', 
                        'tk_chg:track.charge', 
                        'tk_pt:track.pt', 
                        'tk_px:track.px', 
                        'tk_py:track.py', 
                        'tk_pz:track.pz', 
                        'tk_eta:track.eta', 
                        'tk_phi:track.phi', 
                        'tk_theta:track.theta', 
                        'tk_d0dum:track.d0', 
                        'tk_dz:track.dz', 
                        'tk_vx:track.vx', 
                        'tk_vy:track.vy', 
                        'tk_vz:track.vz', 
                        'tk_numvalhits:track.numberOfValidHits', 
                        'tk_numlosthits:track.numberOfLostHits', 
                        'tk_d0dumErr:track.d0Error', 
                        'tk_dzErr:track.dzError', 
                        'tk_ptErr:track.ptError', 
                        'tk_etaErr:track.etaError', 
                        'tk_phiErr:track.phiError', 
                        'tk_numvalPixelhits:track.hitPattern.numberOfValidPixelHits',
                        'tk_numpixelWthMeasr:track.hitPattern.pixelLayersWithMeasurement',
                        'stamu_chi2:standAloneMuon.chi2', 
                        'stamu_ndof:standAloneMuon.ndof', 
                        'stamu_chg:standAloneMuon.charge', 
                        'stamu_pt:standAloneMuon.pt', 
                        'stamu_px:standAloneMuon.px', 
                        'stamu_py:standAloneMuon.py', 
                        'stamu_pz:standAloneMuon.pz', 
                        'stamu_eta:standAloneMuon.eta', 
                        'stamu_phi:standAloneMuon.phi', 
                        'stamu_theta:standAloneMuon.theta', 
                        'stamu_d0dum:standAloneMuon.d0',
                        'stamu_dz:standAloneMuon.dz', 
                        'stamu_vx:standAloneMuon.vx', 
                        'stamu_vy:standAloneMuon.vy', 
                        'stamu_vz:standAloneMuon.vz', 
                        'stamu_numvalhits:standAloneMuon.numberOfValidHits', 
                        'stamu_numlosthits:standAloneMuon.numberOfLostHits', 
                        'stamu_d0dumErr:standAloneMuon.d0Error', 
                        'stamu_dzErr:standAloneMuon.dzError', 
                        'stamu_ptErr:standAloneMuon.ptError', 
                        'stamu_etaErr:standAloneMuon.etaError', 
                        'stamu_phiErr:standAloneMuon.phiError', 
                        'num_matches:numberOfMatches',
                        'isPFMuon:isPFMuon',
                        'isTrackerMuon:isTrackerMuon',
                        'isStandAloneMuon:isStandAloneMuon',
                        'isCaloMuon:isCaloMuon',
                        'isGlobalMuon:isGlobalMuon',
                        'isElectron:isElectron',
                        'isConvertedPhoton:isConvertedPhoton',
                        'isPhoton:isPhoton',
                        'id_All:isGood("All")',
                        'id_AllGlobalMuons:isGood("AllGlobalMuons")',
                        'id_AllStandAloneMuons:isGood("AllStandAloneMuons")',
                        'id_AllTrackerMuons:isGood("AllTrackerMuons")',
                        'id_TrackerMuonArbitrated:isGood("TrackerMuonArbitrated")',
                        'id_AllArbitrated:isGood("AllArbitrated")',
                        'id_GlobalMuonPromptTight:isGood("GlobalMuonPromptTight")',
                        'id_TMLastStationLoose:isGood("TMLastStationLoose")',                        
                        'id_TMLastStationTight:isGood("TMLastStationTight")',
                        'id_TM2DCompatibilityLoose:isGood("TM2DCompatibilityLoose")',
                        'id_TM2DCompatibilityTight:isGood("TM2DCompatibilityTight")',                        
                        'id_TMOneStationLoose:isGood("TMOneStationLoose")',
                        'id_TMOneStationTight:isGood("TMOneStationTight")',
                        'id_TMLastStationOptimizedLowPtLoose:isGood("TMLastStationOptimizedLowPtLoose")',
                        'id_TMLastStationOptimizedLowPtTight:isGood("TMLastStationOptimizedLowPtTight")',
                        'tk_LayersWithMeasurement:track.hitPattern.trackerLayersWithMeasurement',
                        'tk_PixelLayersWithMeasurement:track.hitPattern.pixelLayersWithMeasurement',
                        'tk_ValidStripLayersWithMonoAndStereoHit:track.hitPattern.numberOfValidStripLayersWithMonoAndStereo',
                        'tk_LayersWithoutMeasurement:track.hitPattern.trackerLayersWithoutMeasurement',
                        'tk_ExpectedHitsInner:track.trackerExpectedHitsInner.numberOfHits',
                        'tk_ExpectedHitsOuter:track.trackerExpectedHitsOuter.numberOfHits',
                        'cm_LayersWithMeasurement:combinedMuon.hitPattern.trackerLayersWithMeasurement',
                        'cm_PixelLayersWithMeasurement:combinedMuon.hitPattern.pixelLayersWithMeasurement',
                        'cm_ValidStripLayersWithMonoAndStereoHit:combinedMuon.hitPattern.numberOfValidStripLayersWithMonoAndStereo',
                        'cm_LayersWithoutMeasurement:combinedMuon.hitPattern.trackerLayersWithoutMeasurement',
                        'cm_ExpectedHitsInner:combinedMuon.trackerExpectedHitsInner.numberOfHits',
                        'cm_ExpectedHitsOuter:combinedMuon.trackerExpectedHitsOuter.numberOfHits',
                        'picky_LayersWithMeasurement:pickyMuon.hitPattern.trackerLayersWithMeasurement',
                        'picky_PixelLayersWithMeasurement:pickyMuon.hitPattern.pixelLayersWithMeasurement',
                        'picky_ValidStripLayersWithMonoAndStereoHit:pickyMuon.hitPattern.numberOfValidStripLayersWithMonoAndStereo',
                        'picky_LayersWithoutMeasurement:pickyMuon.hitPattern.trackerLayersWithoutMeasurement',
                        'picky_ExpectedHitsInner:pickyMuon.trackerExpectedHitsInner.numberOfHits',
                        'picky_ExpectedHitsOuter:pickyMuon.trackerExpectedHitsOuter.numberOfHits',
                        'tpfms_LayersWithMeasurement:tpfmsMuon.hitPattern.trackerLayersWithMeasurement',
                        'tpfms_PixelLayersWithMeasurement:tpfmsMuon.hitPattern.pixelLayersWithMeasurement',
                        'tpfms_ValidStripLayersWithMonoAndStereoHit:tpfmsMuon.hitPattern.numberOfValidStripLayersWithMonoAndStereo',
                        'tpfms_LayersWithoutMeasurement:tpfmsMuon.hitPattern.trackerLayersWithoutMeasurement',
                        'tpfms_ExpectedHitsInner:tpfmsMuon.trackerExpectedHitsInner.numberOfHits',
                        'tpfms_ExpectedHitsOuter:tpfmsMuon.trackerExpectedHitsOuter.numberOfHits',
                        'picky_id:pickyMuon.key',
                        'picky_chi2:pickyMuon.chi2',
                        'picky_ndof:pickyMuon.ndof',
                        'picky_chg:pickyMuon.charge',
                        'picky_pt:pickyMuon.pt',
                        'picky_px:pickyMuon.px',
                        'picky_py:pickyMuon.py',
                        'picky_pz:pickyMuon.pz',
                        'picky_eta:pickyMuon.eta',
                        'picky_phi:pickyMuon.phi',
                        'picky_theta:pickyMuon.theta',
                        'picky_d0dum:pickyMuon.d0',
                        'picky_dz:pickyMuon.dz',
                        'picky_vx:pickyMuon.vx',
                        'picky_vy:pickyMuon.vy',
                        'picky_vz:pickyMuon.vz',
                        'picky_numvalhits:pickyMuon.numberOfValidHits',
                        'picky_numlosthits:pickyMuon.numberOfLostHits',
                        'picky_d0dumErr:pickyMuon.d0Error',
                        'picky_dzErr:pickyMuon.dzError',
                        'picky_ptErr:pickyMuon.ptError',
                        'picky_etaErr:pickyMuon.etaError',
                        'picky_phiErr:pickyMuon.phiError',
                        'picky_numvalPixelhits:pickyMuon.hitPattern.numberOfValidPixelHits',
                        'tpfms_id:tpfmsMuon.key',
                        'tpfms_chi2:tpfmsMuon.chi2',
                        'tpfms_ndof:tpfmsMuon.ndof',
                        'tpfms_chg:tpfmsMuon.charge',
                        'tpfms_pt:tpfmsMuon.pt',
                        'tpfms_px:tpfmsMuon.px',
                        'tpfms_py:tpfmsMuon.py',
                        'tpfms_pz:tpfmsMuon.pz',
                        'tpfms_eta:tpfmsMuon.eta',
                        'tpfms_phi:tpfmsMuon.phi',
                        'tpfms_theta:tpfmsMuon.theta',
                        'tpfms_d0dum:tpfmsMuon.d0',
                        'tpfms_dz:tpfmsMuon.dz',
                        'tpfms_vx:tpfmsMuon.vx',
                        'tpfms_vy:tpfmsMuon.vy',
                        'tpfms_vz:tpfmsMuon.vz',
                        'tpfms_numvalhits:tpfmsMuon.numberOfValidHits',
                        'tpfms_numlosthits:tpfmsMuon.numberOfLostHits',
                        'tpfms_d0dumErr:tpfmsMuon.d0Error',
                        'tpfms_dzErr:tpfmsMuon.dzError',
                        'tpfms_ptErr:tpfmsMuon.ptError',
                        'tpfms_etaErr:tpfmsMuon.etaError',
                        'tpfms_phiErr:tpfmsMuon.phiError',
                        'tpfms_numvalPixelhits:tpfmsMuon.hitPattern.numberOfValidPixelHits',
                        'dB:dB',
                        'numberOfMatchedStations:numberOfMatchedStations',
                    )
                ),
                Class = cms.string('pat::Muon')
                ),

                 mets = cms.PSet(
                  src = cms.InputTag("slimmedMETs"),
                   leaves = cms.PSet(
                    vars = cms.vstring('et:et', 
                        'phi:phi', 
                        'ex:px', 
                        'ey:py', 
                        'gen_et:genMET.et', 
                        'gen_phi:genMET.phi',
                        'sign:metSignificance',
                        'sumEt:sumEt', 
                        'unCPhi:uncorrectedPhi', 
                        'unCPt:uncorrectedPt')
                ),
                Class = cms.string('pat::MET')
            ),

            photons = cms.PSet(
                src = cms.InputTag("slimmedPhotons"),
                leaves = cms.PSet(
                    basicKinematicLeaves,
                    vars= cms.vstring('hadOverEM:hadronicOverEm',
                                      'nPFmatch:numberOfSourceCandidatePtrs()',
                                      'hadTowOverEM:hadTowOverEm',
                                      'scEnergy:superCluster.energy',
                                      'scRawEnergy:superCluster.rawEnergy',
                                      'scEta:superCluster.position.eta',
                                      'scPhi:superCluster.position.phi',
                                      'scEtaWidth:superCluster.etaWidth',
                                      'scPhiWidth:superCluster.phiWidth',
                                      'tIso:trackIso',
                                      'ecalIso:ecalIso',
                                      'hcalIso:hcalIso',
                                      
                                      #'isoEcalRecHit:isolationEcalRecHit',
                                      #'isoHcalRecHit:isolationHcalRecHit',
                                      #'isoSolidTrkCone:isolationSolidTrkCone',
                                      #'isoHollowTrkCone:isolationHollowTrkCone',
                                      #'nTrkSolidCone:nTrkSolidCone',
                                      #'nTrkHollowCone:nTrkHollowCone',
                                      
                                      'isoEcalRecHitDR04:ecalRecHitSumEtConeDR04',
                                      'isoHcalRecHitDR04:hcalTowerSumEtConeDR04',
                                      'isoSolidTrkConeDR04:trkSumPtSolidConeDR04',
                                      'isoHollowTrkConeDR04:trkSumPtHollowConeDR04',
                                      'nTrkSolidConeDR04:nTrkSolidConeDR04',
                                      'nTrkHollowConeDR04:nTrkSolidConeDR04',
                                      'isoEcalRecHitDR03:ecalRecHitSumEtConeDR03',
                                      'isoHcalRecHitDR03:hcalTowerSumEtConeDR03',
                                      'isoSolidTrkConeDR03:trkSumPtSolidConeDR03',
                                      'isoHollowTrkConeDR03:trkSumPtHollowConeDR03',
                                      'nTrkSolidConeDR03:nTrkSolidConeDR03',
                                      'nTrkHollowConeDR03:nTrkSolidConeDR03',
                                      

                                      #'isAlsoElectron:isAlsoElectron',
                                      'isAlsoElectron:isElectron',
                                      
                                      'hasPixelSeed:hasPixelSeed',
                                      #'isConverted:isConverted',
                                      'isConverted:isConvertedPhoton',
                                      'isEBGap:isEBGap',
                                      'isEEGap:isEEGap',
                                      'isEBEEGap:isEBEEGap',
                                      'isEBPho:isEB',#changed from isEBPho
                                      'isEEPho:isEE',#changed from isEEPho
                                      #'isLooseEM:isLooseEM',
                                      #'isLoosePhoton:isLoosePhoton',
                                      #'isTightPhoton:isTightPhoton',
                                      'isLoosePhoton:photonID("PhotonCutBasedIDLoose")',
                                      'isTightPhoton:photonID("PhotonCutBasedIDLoose")',
                                      #Currently (28-07) all photons are defined as LooseEM, but this will be added again as
                                      # they are going to relax pre-selection cuts on the photon 
                                      #'isLooseEM:photonID()',
                                      'maxEnergyXtal:maxEnergyXtal',
                                      'e1x5:e1x5',
                                      'e2x5:e2x5',
                                      'e3x3:e3x3',
                                      'e5x5:e5x5',
                                      'sigmaEtaEta:sigmaEtaEta',
                                      'sigmaIetaIeta:sigmaIetaIeta',
                                      'r9:r9',
                                      'gen_et:genPhoton.et',
                                      'gen_eta:genPhoton.eta',
                                      'gen_phi:genPhoton.phi',
                                      'gen_id:genPhoton.pdgId'
                                      )
                                      ),
                    
                Class = cms.string('pat::Photon')
            ),


            mc_doc = cms.PSet(
                src = cms.InputTag("prunedGenParticles"),
                leaves = cms.PSet(
                    vars = cms.vstring(
                        'id:pdgId',
                        'pt:pt',
                        'px:px',
                        'py:py',
                        'pz:pz',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'energy:energy',
                        'status:status',
                        'charge:charge',
                        'mother_id:mother.pdgId',
                        'grandmother_id:mother.mother.pdgId',
                        'ggrandmother_id:mother.mother.mother.pdgId',
                        'mother_pt:mother.pt',
                        'vertex_x:vertex.x',
                        'vertex_y:vertex.y',
                        'vertex_z:vertex.z',
                        'mass:mass',
                        'numOfDaughters:numberOfDaughters',
                        'numOfMothers:numberOfMothers'
                    )
                ),
                #selection = cms.string('status=3'),  ## We'll cut on something later
                Class = cms.string('reco::GenParticle')
            ),

            mc_final = cms.PSet(
                src = cms.InputTag("packedGenParticles"),
                leaves = cms.PSet(
                    vars = cms.vstring(
                        'id:pdgId',
                        'pt:pt',
                        'px:px',
                        'py:py',
                        'pz:pz',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'energy:energy',
                        'status:status',
                        'charge:charge',
                        'mother_id:mother.pdgId',
                        'grandmother_id:mother.mother.pdgId',
                        'ggrandmother_id:mother.mother.mother.pdgId',
                        'mother_pt:mother.pt',
                        'vertex_x:vertex.x',
                        'vertex_y:vertex.y',
                        'vertex_z:vertex.z',
                        'mass:mass',
                        'numOfDaughters:numberOfDaughters',
                        'numOfMothers:numberOfMothers'
                    )
                ),
                Class = cms.string('pat::PackedGenParticle')
            ),

             mc_mus = cms.PSet(
                src = cms.InputTag("prunedGenParticles"),
                leaves = cms.PSet(
                    vars = cms.vstring('id:pdgId',
                        'pt:pt',
                        'px:px',
                        'py:py',
                        'pz:pz',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'status:status',
                        'energy:energy',
                        'charge:charge',
                        'mother_id:mother.pdgId',
                        'mother_pt:mother.pt',
                        'grandmother_id:mother.mother.pdgId',
                        'ggrandmother_id:mother.mother.mother.pdgId',
                        'vertex_x:vertex.x',
                        'vertex_y:vertex.y',
                        'vertex_z:vertex.z',
                        'mass:mass',
                        'numOfDaughters:numberOfDaughters')
                ),
                selection = cms.string('(pdgId=13 | pdgId=-13)'),
                Class = cms.string('reco::GenParticle')
            ),

            mc_electrons = cms.PSet(
                src = cms.InputTag("prunedGenParticles"),
                leaves = cms.PSet(
                    vars = cms.vstring('id:pdgId',
                        'pt:pt',
                        'px:px',
                        'py:py',
                        'pz:pz',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'status:status',
                        'energy:energy',
                        'charge:charge',
                        'mother_id:mother.pdgId',
                        'mother_pt:mother.pt',
                        'grandmother_id:mother.mother.pdgId',
                        'ggrandmother_id:mother.mother.mother.pdgId',
                        'vertex_x:vertex.x',
                        'vertex_y:vertex.y',
                        'vertex_z:vertex.z',
                        'mass:mass',
                        'numOfDaughters:numberOfDaughters')
                ),
                selection = cms.string('(pdgId=11 | pdgId=-11)'),
                Class = cms.string('reco::GenParticle')
            ),

            mc_taus = cms.PSet(
                src = cms.InputTag("prunedGenParticles"),
                leaves = cms.PSet(
                    vars = cms.vstring('id:pdgId',
                        'pt:pt',
                        'px:px',
                        'py:py',
                        'pz:pz',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'status:status',
                        'energy:energy',
                        'charge:charge',
                        'mother_id:mother.pdgId',
                        'mother_pt:mother.pt',
                        'grandmother_id:mother.mother.pdgId',
                        'ggrandmother_id:mother.mother.mother.pdgId',
                        'vertex_x:vertex.x',
                        'vertex_y:vertex.y',
                        'vertex_z:vertex.z',
                        'mass:mass',
                        'numOfDaughters:numberOfDaughters')
                ),
                selection = cms.string('(pdgId=15 | pdgId=-15)'),
                Class = cms.string('reco::GenParticle')
            ),

           mc_photons = cms.PSet(
                src = cms.InputTag("prunedGenParticles"),
                leaves = cms.PSet(
                    vars = cms.vstring('id:pdgId',
                        'pt:pt',
                        'px:px',
                        'py:py',
                        'pz:pz',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'status:status',
                        'energy:energy',
                        'charge:charge',
                        'mother_id:mother.pdgId',
                        'mother_pt:mother.pt',
                        'grandmother_id:mother.mother.pdgId',
                        'ggrandmother_id:mother.mother.mother.pdgId',
                        'vertex_x:vertex.x',
                        'vertex_y:vertex.y',
                        'vertex_z:vertex.z',
                        'mass:mass',
                        'numOfDaughters:numberOfDaughters')
                ),
                selection = cms.string('(pdgId=22) & pt>10'),
                Class = cms.string('reco::GenParticle')
            ),

            mc_nutaus = cms.PSet(
                src = cms.InputTag("prunedGenParticles"),
                leaves = cms.PSet(
                    vars = cms.vstring('id:pdgId',
                        'pt:pt',
                        'px:px',
                        'py:py',
                        'pz:pz',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'status:status',
                        'energy:energy',
                        'charge:charge',
                        'mother_id:mother.pdgId',
                        'mother_pt:mother.pt',
                        'grandmother_id:mother.mother.pdgId',
                        'ggrandmother_id:mother.mother.mother.pdgId',
                        'vertex_x:vertex.x',
                        'vertex_y:vertex.y',
                        'vertex_z:vertex.z',
                        'mass:mass',
                        'numOfDaughters:numberOfDaughters')
                ),
                selection = cms.string('(pdgId=16 | pdgId=-16)'),
                Class = cms.string('reco::GenParticle')
            ),

            mc_nues = cms.PSet(
                src = cms.InputTag("prunedGenParticles"),
                leaves = cms.PSet(
                    vars = cms.vstring('id:pdgId',
                        'pt:pt',
                        'px:px',
                        'py:py',
                        'pz:pz',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'status:status',
                        'energy:energy',
                        'charge:charge',
                        'mother_id:mother.pdgId',
                        'mother_pt:mother.pt',
                        'grandmother_id:mother.mother.pdgId',
                        'ggrandmother_id:mother.mother.mother.pdgId',
                        'vertex_x:vertex.x',
                        'vertex_y:vertex.y',
                        'vertex_z:vertex.z',
                        'mass:mass',
                        'numOfDaughters:numberOfDaughters')
                ),
                selection = cms.string('(pdgId=12 | pdgId=-12)'),
                Class = cms.string('reco::GenParticle')
            ),

            mc_numus = cms.PSet(
                src = cms.InputTag("prunedGenParticles"),
                leaves = cms.PSet(
                    vars = cms.vstring('id:pdgId',
                        'pt:pt',
                        'px:px',
                        'py:py',
                        'pz:pz',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'status:status',
                        'energy:energy',
                        'charge:charge',
                        'mother_id:mother.pdgId',
                        'mother_pt:mother.pt',
                        'grandmother_id:mother.mother.pdgId',
                        'ggrandmother_id:mother.mother.mother.pdgId',
                        'vertex_x:vertex.x',
                        'vertex_y:vertex.y',
                        'vertex_z:vertex.z',
                        'mass:mass',
                        'numOfDaughters:numberOfDaughters')
                ),
                selection = cms.string('(pdgId=14 | pdgId=-14)'),
                Class = cms.string('reco::GenParticle')
            ),

             taus = cms.PSet(
                 src = cms.InputTag("slimmedTaus"),
                 leaves = cms.PSet(
                     #basicKinematicLeaves,
                     vars = cms.vstring(
                         'nPFmatch:numberOfSourceCandidatePtrs()',
                         'status:status',
                         'phi:phi',
                         'pt:pt',
                         'pz:pz',
                         'px:px',
                         'py:py',
                         'eta:eta',
                         'theta:theta',
                         'et:et',
                         'energy:energy',
                         'charge:charge',
                         'emf:emFraction',
                         'hcalTotOverPLead:hcalTotOverPLead',
                         'hcalMaxOverPLead:hcalMaxOverPLead',
                         'hcal3x3OverPLead:hcal3x3OverPLead',
                         'ecalStripSumEOverPLead:ecalStripSumEOverPLead',
                         'elecPreIdOutput:electronPreIDOutput',
                         'elecPreIdDecision:electronPreIDDecision',
                         'leadPFChargedHadrCand_pt:leadPFChargedHadrCand.pt',
                         'leadPFChargedHadrCand_charge:leadPFChargedHadrCand.charge',
                         'leadPFChargedHadrCand_eta:leadPFChargedHadrCand.eta',
                         'leadPFChargedHadrCand_ECAL_eta:leadPFChargedHadrCand.positionAtECALEntrance.eta',
                         'leadPFChargedHadrCand_phi:leadPFChargedHadrCand.phi',
                         'isoPFGammaCandsEtSum:isolationPFGammaCandsEtSum',
                         'isoPFChargedHadrCandsPtSum:isolationPFChargedHadrCandsPtSum',
                         'leadingTrackFinding:tauID("leadingTrackFinding")',
                         'leadingTrackPtCut:tauID("leadingTrackPtCut")',
                         'trackIsolation:tauID("trackIsolation")',
                         'ecalIsolation:tauID("ecalIsolation")',
                         'byIsolation:tauID("byIsolation")', 
                         'againstElectron:tauID("againstElectron")',
                         'againstMuon:tauID("againstMuon")',
                         'taNC_quarter:tauID("byTaNCfrQuarterPercent")',
                         'taNC_one:tauID("byTaNCfrOnePercent")',
                         'taNC_half:tauID("byTaNCfrHalfPercent")',
                         'taNC_tenth:tauID("byTaNCfrTenthPercent")',
                         'taNC:tauID("byTaNC")',
                         'byIsoUsingLeadingPi:tauID("byIsolationUsingLeadingPion")',
                         'tkIsoUsingLeadingPi:tauID("trackIsolationUsingLeadingPion")',
                         'ecalIsoUsingLeadingPi:tauID("ecalIsolationUsingLeadingPion")',
                         'againstElectronLoose:tauID("againstElectronLoose")',
                         'againstElectronMedium:tauID("againstElectronMedium")',
                         'againstElectronTight:tauID("againstElectronTight")',
                         'againstElectronMVA:tauID("againstElectronMVA")',
                         'againstMuonLoose:tauID("againstMuonLoose")',
                         'againstMuonMedium:tauID("againstMuonMedium")',
                         'againstMuonTight:tauID("againstMuonTight")',
                         'decayModeFinding:tauID("decayModeFinding")',
                         'byVLooseIsolation:tauID("byVLooseIsolation")',
                         'byLooseIsolation:tauID("byLooseIsolation")',
                         'byMediumIsolation:tauID("byMediumIsolation")',
                         'byTightIsolation:tauID("byTightIsolation")',
                         'byVLooseIsolationDeltaBetaCorr:tauID("byVLooseIsolationDeltaBetaCorr")',
                         'byLooseIsolationDeltaBetaCorr:tauID("byLooseIsolationDeltaBetaCorr")',
                         'byMediumIsolationDeltaBetaCorr:tauID("byMediumIsolationDeltaBetaCorr")',
                         'byTightIsolationDeltaBetaCorr:tauID("byTightIsolationDeltaBetaCorr")',
                         'signalPFChargedHadrCandsSize:signalPFChargedHadrCands.size',
                         'muDecision:muonDecision',
                         'Nprongs:signalTracks.size'
                     )
                 ),
                 selection = cms.string('pt>10'),
                 Class = cms.string('pat::Tau')
             ),

            els = cms.PSet(
                src = cms.InputTag('slimmedElectrons'),
                leaves = cms.PSet(
                    basicKinematicLeaves,
                    vars = cms.vstring(#'id:leptonID', 
                        'nPFmatch:numberOfSourceCandidatePtrs()',
                        'pfIsolationR03_sumChargedHadronPt:pfIsolationVariables.sumChargedHadronPt',
                        'pfIsolationR03_sumNeutralHadronEt:pfIsolationVariables.sumNeutralHadronEt',
                        'pfIsolationR03_sumPhotonEt:pfIsolationVariables.sumPhotonEt',
                        'pfIsolationR03_sumPUPt:pfIsolationVariables.sumPUPt',
                        'full5x5_sigmaIetaIeta:full5x5_sigmaIetaIeta',
                        'gen_id:genLepton.pdgId',
                        'gen_phi:genLepton.phi',
                        'gen_pt:genLepton.pt',
                        'gen_pz:genLepton.pz',
                        'gen_px:genLepton.px',
                        'gen_py:genLepton.py',
                        'gen_eta:genLepton.eta',
                        'gen_theta:genLepton.theta',
                        'gen_et:genLepton.et',                       
                        'gen_mother_id:genLepton.mother.pdgId',
                        'gen_mother_phi:genLepton.mother.phi',
                        'gen_mother_pt:genLepton.mother.pt',
                        'gen_mother_pz:genLepton.mother.pz',
                        'gen_mother_px:genLepton.mother.px',
                        'gen_mother_py:genLepton.mother.py',
                        'gen_mother_eta:genLepton.mother.eta',
                        'gen_mother_theta:genLepton.mother.theta',
                        'gen_mother_et:genLepton.mother.et',                       
                        'tightId:electronID("eidTight")',
                        'looseId:electronID("eidLoose")',
                        'robustTightId:electronID("eidRobustTight")',
                        'robustLooseId:electronID("eidRobustLoose")',
                        'robustHighEnergyId:electronID("eidRobustHighEnergy")',
                        'simpleEleId95relIso:electronID("simpleEleId95relIso")',
                        'simpleEleId90relIso:electronID("simpleEleId90relIso")',
                        'simpleEleId85relIso:electronID("simpleEleId85relIso")',
                        'simpleEleId80relIso:electronID("simpleEleId80relIso")',
                        'simpleEleId70relIso:electronID("simpleEleId70relIso")',
                        'simpleEleId60relIso:electronID("simpleEleId60relIso")',
                        'simpleEleId95cIso:electronID("simpleEleId95cIso")',
                        'simpleEleId90cIso:electronID("simpleEleId90cIso")',
                        'simpleEleId85cIso:electronID("simpleEleId85cIso")',
                        'simpleEleId80cIso:electronID("simpleEleId80cIso")',
                        'simpleEleId70cIso:electronID("simpleEleId70cIso")',
                        'simpleEleId60cIso:electronID("simpleEleId60cIso")',
                        'cIso:caloIso', 
                        'tIso:trackIso', 
                        'ecalIso:ecalIso',
                        'hcalIso:hcalIso',
                        'chi2:gsfTrack.chi2', 
#                        'class:classification', 
                        'charge:charge', 
                        'caloEnergy:caloEnergy',
                        'hadOverEm:hadronicOverEm',
                        'hcalOverEcalBc:hcalOverEcalBc', 
                        'eOverPIn:eSuperClusterOverP', 
                        'eSeedOverPOut:eSeedClusterOverPout', 
                        'sigmaEtaEta:scSigmaEtaEta',
                        'sigmaIEtaIEta:scSigmaIEtaIEta',
                        'scEnergy:superCluster.energy',
                        'scRawEnergy:superCluster.rawEnergy',
                        'scSeedEnergy:superCluster.seed.energy',
                        'scEta:superCluster.position.eta',
                        'scPhi:superCluster.position.phi',
                        'scEtaWidth:superCluster.etaWidth',
                        'scPhiWidth:superCluster.phiWidth',
                        'scE1x5:scE1x5',
                        'scE2x5Max:scE2x5Max',
                        'scE5x5:scE5x5',
                        'isEB:isEB',
                        'isEE:isEE',
                        'dEtaIn:deltaEtaSuperClusterTrackAtVtx', 
                        'dPhiIn:deltaPhiSuperClusterTrackAtVtx', 
                        'dEtaOut:deltaEtaSeedClusterTrackAtCalo', 
                        'dPhiOut:deltaPhiSeedClusterTrackAtCalo', 
                        'numvalhits:gsfTrack.numberOfValidHits', 
                        'numlosthits:gsfTrack.numberOfLostHits', 
                        #'numCluster:numberOfClusters', 
                        'basicClustersSize:basicClustersSize',
                        'tk_pz:gsfTrack.pz',
                        'tk_pt:gsfTrack.pt', 
                        'tk_phi:gsfTrack.phi', 
                        'tk_eta:gsfTrack.eta', 
                        'd0dum:gsfTrack.d0', 
                        'dz:gsfTrack.dz', 
                        'vx:gsfTrack.vx', 
                        'vy:gsfTrack.vy', 
                        'vz:gsfTrack.vz', 
                        'ndof:gsfTrack.ndof', 
                        'ptError:gsfTrack.ptError', 
                        'd0dumError:gsfTrack.d0Error', 
                        'dzError:gsfTrack.dzError', 
                        'etaError:gsfTrack.etaError', 
                        'phiError:gsfTrack.phiError', 
                        'tk_charge:gsfTrack.charge',
			'core_ecalDrivenSeed:core.ecalDrivenSeed',
                        'n_inner_layer:gsfTrack.trackerExpectedHitsInner.numberOfHits',
                        'n_outer_layer:gsfTrack.trackerExpectedHitsOuter.numberOfHits',
                        'ctf_tk_id:closestCtfTrackRef.key',
                        'ctf_tk_charge:closestCtfTrackRef.charge',
                        'ctf_tk_eta:closestCtfTrackRef.eta',
                        'ctf_tk_phi:closestCtfTrackRef.phi',
                        'fbrem:fbrem',
                        'shFracInnerHits:shFracInnerHits',                        
                        'dr03EcalRecHitSumEt:dr03EcalRecHitSumEt',
                        'dr03HcalTowerSumEt:dr03HcalTowerSumEt',
                        'dr03HcalDepth1TowerSumEt:dr03HcalDepth1TowerSumEt',
                        'dr03HcalDepth2TowerSumEt:dr03HcalDepth2TowerSumEt',
                        'dr03TkSumPt:dr03TkSumPt',
                        'dr04EcalRecHitSumEt:dr03EcalRecHitSumEt',
                        'dr04HcalTowerSumEt:dr03HcalTowerSumEt',
                        'dr04HcalDepth1TowerSumEt:dr04HcalDepth1TowerSumEt',
                        'dr04HcalDepth2TowerSumEt:dr04HcalDepth2TowerSumEt',
                        'dr04TkSumPt:dr04TkSumPt',
                        'cpx:trackMomentumAtCalo.x', 
                        'cpy:trackMomentumAtCalo.y', 
                        'cpz:trackMomentumAtCalo.z', 
                        'vpx:trackMomentumAtVtx.x', 
                        'vpy:trackMomentumAtVtx.y', 
                        'vpz:trackMomentumAtVtx.z',
                        'cx:TrackPositionAtCalo.x', 
                        'cy:TrackPositionAtCalo.y', 
                        'cz:TrackPositionAtCalo.z', 
                        #'IDRobust:electronIDRobust'
                        'PATpassConversionVeto:passConversionVeto'
                        )
                ),
                Class = cms.string('pat::Electron')
            ),

            jets_AK4 = cms.PSet(
                src = cms.InputTag("slimmedJets"),
                leaves = cms.PSet(
                    #basicKinematicLeaves,
                    vars = cms.vstring(
                        'status:status',
                        'phi:phi',
                        'pt:pt',
                        'pz:pz',
                        'px:px',
                        'py:py',
                        'eta:eta',
                        'theta:theta',
                        'et:et',
                        'energy:energy',
                        'parton_Id:genParton.pdgId',
                        'parton_motherId:genParton.mother.pdgId',
                        'parton_pt:genParton.pt',
                        'parton_phi:genParton.phi',
                        'parton_eta:genParton.eta',
                        'parton_Energy:genParton.energy',
                        'parton_mass:genParton.mass',
                        #'parton_motherID:genParton.mother.pdgId',
                        #'parton_grandmotherID:genParton.mother.mother.pdgId',
                        'gen_et:genJet.et',
                        'gen_pt:genJet.pt',
                        'gen_eta:genJet.eta',
                        'gen_phi:genJet.phi',
                        'gen_mass:genJet.mass',
                        'gen_Energy:genJet.energy',
                        'gen_Id:genJet.pdgId',
                        'gen_motherID:genJet.mother.pdgId',
                        'gen_threeCharge:genJet.threeCharge',
                        'partonFlavour:partonFlavour',  #TL add
                        'btag_TC_highPur:bDiscriminator("trackCountingHighPurBJetTags")', # TL add: b-tagging info (9lines)
                        'btag_TC_highEff:bDiscriminator("trackCountingHighEffBJetTags")',
                        'btag_jetProb:bDiscriminator("jetProbabilityBJetTags")',
                        'btag_jetBProb:bDiscriminator("jetBProbabilityBJetTags")',
                        'btag_softEle:bDiscriminator("softElectronByPtBJetTags")',
                        'btag_softMuon:bDiscriminator("softMuonBJetTags")',
                        'btag_secVertexHighPur:bDiscriminator("simpleSecondaryVertexHighPurBJetTags")',
                        'btag_secVertexHighEff:bDiscriminator("simpleSecondaryVertexHighEffBJetTags")',
                        'btag_secVertexCombined:bDiscriminator("combinedSecondaryVertexBJetTags")',
                        'jetCharge:jetCharge',
                        'chgEmE:chargedEmEnergy',
                        'chgHadE:chargedHadronEnergy',
                        'photonEnergy:photonEnergy',
                        'chgMuE:chargedMuEnergy',
                        'chg_Mult:chargedMultiplicity',
                        'neutralEmE:neutralEmEnergy',
                        'neutralHadE:neutralHadronEnergy',
                        'neutral_Mult:neutralMultiplicity',
                        'mu_Mult:muonMultiplicity',
                        'emf:emEnergyFraction',
                        'ehf:energyFractionHadronic',
                        'n60:n60',
                        'n90:n90',
                        'etaetaMoment:etaetaMoment',
                        'etaphiMoment:etaphiMoment',
                        'phiphiMoment:phiphiMoment',
                        'n90Hits:jetID.n90Hits',
                        'fHPD:jetID.fHPD',
                        'fRBX:jetID.fRBX',
                        'hitsInN90:jetID.hitsInN90',
                        'nECALTowers:jetID.nECALTowers',
                        'nHCALTowers:jetID.nHCALTowers',
                        'fSubDetector1:jetID.fSubDetector1',
                        'fSubDetector2:jetID.fSubDetector2',
                        'fSubDetector3:jetID.fSubDetector3',
                        'fSubDetector4:jetID.fSubDetector4',
                        'area:towersArea',
                        'corrFactorRaw:jecFactor(0)',
                        'rawPt:jecFactor(0)*pt',
                        'mass:mass'
                    )
        	),
                selection = cms.string('pt*jecFactor(0)>10.0 | pt>20.0'),
                Class = cms.string('pat::Jet')
            ),
            
          pfcand = cms.PSet(
                src = cms.InputTag('packedPFCandidates'),
                leaves = cms.PSet(
                    vars = cms.vstring(
                        'pdgId:pdgId',
                        'pt:pt',
                        'pz:pz',
                        'px:px',
                        'py:py',
                        'eta:eta',
                        'phi:phi',
                        'theta:theta',
                        'energy:energy',
                        'charge:charge'
                     )
                ),
                selection = cms.string('pt>10'),
                Class = cms.string('pat::PackedCandidate')
            ),
        ),
        ComponentName = cms.string('CompleteNTupler'),
        AdHocNPSet = cms.PSet(treeName = cms.string('eventA')),
        useTFileService = cms.bool(True), ## false for EDM; true for non EDM
    )
)



